import LocalizedStrings from "react-localization";

let strings = new LocalizedStrings({
  ar: {
    pending: "قيد الانتظار",
    confirmedByInvestor: "تم التأكيد من طرف المستثمر (مؤسسة التمويل)",
    loans: "القروض",
    login: "دخول",
    borrow: "اقترض",
    invest: "استثمر",
    getStart: "ابدأ",
    selectLanguage: "اختر اللغة",
    backersListFor: "قائمة الداعمين ل",
    noDataToShow: "لا يوجد بيانات",
    loanInformation: "معلومات القروض",
    totalFunded: "إجمالي التمويل",
    totalRepaid: "إجمالي المدفوعات",
    totalRepaidSmall: "أجمالي المدفوعات",
    totalValue: "أجمالي المبلغ",
    repaidProposals: "القروض المدفوعه",
    confirmation: "تأكيد",
    yes: "نعم",
    no: "لا",
    addNewProposal: "أضف مسودة طلب جديدة",
    addNewProposalDesc:
      "أختر ذلك العنصر لتبدأ كتابة مسودة جديدة تلك هي اول خطوة نحو قرضك",
    allProposals: "أختار الكل",
    allProposalsDesc: "اختر ذلك العنصر لرؤية جميع قروضك",
    selectDraftedProposals: "أختر القروض التي في حالة المسودة",
    selectDraftedProposalsDesc: `أختر ذلك العنصر لرؤية جميع المسودات المسودة هي اول حاله للقرض المستخدم يستطيع تعديل و مسح او نشر المسودات الخاصة به`,
    selectPublishedProposals: "اختار القروض التي تم نشرها",
    selectPublishedProposalsDesc: `اختر ذلك العنصر لرؤية القروض التي تم نشرها فقط
    النشر هوالحالة الثانية للقرض
    القروض التي تم نشرها يستطيع المستثمرون رؤيتها في صفحة أستثمر
    يستطيع المستخدم تعديل و الغاء نشر الطلبات التي في حالة النشر
    يستطيع المستخدم دعوة المستثمرين`,
    selectLockedProposals: " أختر القروض في حالة القفل",
    selectLockedProposalsDesc: `أختار ذلك العنصرلرؤية القروض في حالة الاقفال
    حالة القفل هي ثالث حالة للقرض
    القفل معناه ان القرض حاليا اصبح عقدا غير  قابل للتعديل لانه قام مستثمر ما بضخ اموال بداخلة
    القفل معناه ان القرض اصبح مدعوما من بعض المتثمرين ولكن لم يصل لمبلغ القرض
    المستخدم لا يستطيع مسح او عدم نشر او تعديل القرض في حالة القفل
    المستخدم يستطيع رؤية ومحادثة ودعوة المستثمرين`,
    selectBackedProposals: "أختر القروض في حالة الدعم",
    selectBackedProposalsDesc: `ختر ذلك العنصر لرؤية جميع القروض في حاله الدعم
    القرض المدعوم هو رابع حالة للقرض
    الدعم معناها ان القرض قد حصل المبلغ كامل
    المستخدم لا يستطيع تعديل او تغيير حالة القرض
    المستخدم يستطيع رؤية و محادثة المستثمرين`,
    selectFundedProposals: " أختر القروض الممولة",
    selectFundedProposalsDesc: `أختر ذلك العنصر لرؤية جميع القروض الممولة
    القرض الممول هو خامس حالة للقرض
    ممول تعني ان القرض قد تمت الموافقة علية والمستخدم يستطيع سحب المال
    المستخدم يستطيع سحب المال الي حسابة البنكي
    المستخدم لا يستطيع تعديل او الغاء نشر القرض
    المستخدم يستطيع رؤية ومحادثة المستثمرين`,
    selectRepaidProposals: "أختر القروض التي تم دفعها",
    selectRepaidProposalsDesc: `أختر ذلك العنصر لرؤية جميع القروض المدفوعة
    القرض المدفوع هو أخر حالة للقرض
    تعني ان القرض تم دفعه
    المستخدم لا يستطيع حذف او الغاء نشر القرض في هذه الحالة
    يستطيع المستخدم رؤية ومحادثة المستثمرين
    `,
    sendThankYouNote: "إرسل رسالة شكر",
    invitationDate: "تاريخ إرسال الدعوة",
    investedAmount: "المبلغ الذي تم استثماره",
    active: "نشط",
    progress: "تحت الانشاء",
    openDLNDocs: "شاهد دليل استخدام ومعلومات DLN",
    userCanCheckDLNDocumentation:
      "المستخدم يستطيع رؤية دليل استخدام ومعلومات عن DLN",
    phone: "رقم التليفون:  ",
    email: "البريد الالكتروني:  ",
    poweredByDLN: "Powered by DLN-DAO",
    investmentIncome: "دخل الاستثمار",
    activeROÍ: "نشط ROÍ",
    myInvestmentOÍ: "استثماراتي",
    userName: "اسم المستخدم",
    password: "كلمة المرور",
    confirmPassword: "إعاده كلمه المرور",
    profileImage: "صورة المستخدم",
    firstName: "الاسم الاول:",
    lastName: "الاسم الاخير:",
    myBio: "نبذة شخصية:",
    required: "مطلوب",
    iHaveReadAndAgree: "لقد قرات ووافقت علي الشروط والاحكام",
    createProfile: "إنشاء حساب",
    openHelpMode: "فتح وضع التجربه",
    messageTheInvestors: "راسل الممولين",
    loanValue: "قيمه القرض",
    yourAmoutnBackedSucc: "تم دعم قرضك بالكامل",
    letsInvest: "أستثمر ف",
    inviteAll: "دعوة الكل",
    letsInviteBackers: "ادعو ممولين",
    repaymentAmount: "مبلغ السداد",
    goBack: "رجوع",
    transactionHistory: "تاريخ المعاملات",
    withDraw: "سحب الاموال",
    //proposals card field
    userCanDelete: "يستطيع المستخدم حذف القروض في حالة المسودة او النشر فقط",
    deleteYourProposal: "حذف هذا القرض",
    draftedProposal: "مسودة قرض",
    puplishedProposal: "قرض تم نشرة",
    lockedProposal: "قرض مغلق",
    fundedProposal: "قرض ممول",
    backedProposal: "قرض مدعوم",
    investProposal: "إستثمر في قرض",
    unpublishProposal: "إلغاء نشر القرض",
    saveProposalAsDraft: " حفظ بيانات القرض",
    saveProposalDesc: " يمكنك حفظ بيانات القرض في مسودة",
    proposalInProgress: "القرض قيد التنفيذ",
    proposalAmount: "رصيد القرض",
    proposalDesc: "شرح القرض",
    activeProposals: "قروض نشطه",
    totalProposalsValue: " إجمالي مبلغ القروض",
    proposals: "القروض",
    proposalName: "إسم القرض",
    enterAmountOfMoney: "أدخل كمية المال التي تريد طلبها؟",
    enterMonthsToRepy: "أدخل عدد الشهور التي سوف تسدد القرض خلالها",
    monthsToPayment: "عدد الشهور التي سوف تسدد القرض خلالها",
    proposalsDate: "تاريخ القرض",
    whenYouNeedToGetYourMoney: "متي تريد الحصول علي القرض؟",
    describeYourProposalAndYourNeeds: "أشرح الغرض من القرض و لماذا تحتاج لة",
    proposalPic: "الصورة الخاصة بالقرض",
    editYourProposal: "عدل قرضك",
    publishYourProposal: "قم بنشر قرضك",
    userCanPublishHisDraftProposal:
      "المستخدم يستطيع نشر مسودة القرض لتصبح في حالة النشر",
    messageInvestor: "أرسل رسالة لمستثمر",
    userCanSelectAnyInvestor: "المستخدم يستطيع اختيار مستثمر لارسال رسالة له",
    inviteAnInvestor: "ارسل دعوة لمستثمر",
    userCanInviteAnInvestorToBack:
      "المستخدم يستطيع أرسال دعوة لمستثمرين ليقوموا بدعم قرضه",
    UnpublishYourPublishedProposal: " قم بالغاء نشر القرض الخاص بكl",
    unPublishYourProposalsDesc:
      "يستطيع المستخدم إلغاء نشر قرضه الذي في حالة النشر فقط",
    checkYourBackedAmount: " تحفق من مال الدعم الذي جمعته حتي الان",
    collectedAmount: "المبلغ المحصل",
    checkYourBackedAmountDesc:
      "المستخدم يستطيع معرفة كم من المال الجمع قام بتجميعه من المستثمرين",
    seeBackers: "قائمه المستثمرين",
    userCanSeeHisBackersDesc: "رؤية التحقق من المستثمرين في القرض الخاص بك",
    withDrawYourMoney: "سحب الأموال - اسحب أموال قرضك",
    withDrawHisMoneyDesc: `المستخدم يستطيع سحب الأموال الخاصة به
    سحب الأموال مع القروض صاحبة حالة (ممول)`,
    repayYourLoan: " سدد القرض",
    userCanRepayDesc:
      "يستطيع المستخدم أن يدفع يسدد الدفعات الشهرية المستحقة علي قرضه",
    investDesc: "المستخدم يستطيع الإستثمار في أي قرض",
    approveProposal: "الموافقة علي القرض",
    userCanApproveProposal:
      "المؤسسة الخاصة بالتمويل تستطيع الموافقة علي القروض المعروضة عليها",
    ignoreProposal: "تجاهل القرض",
    ignoreProposalDesc:
      "المستخدم والمؤسسات يستطيعون تجاهل القروض التي لا يريدونها",
    forgotPassword: "هل نسيت كلمة المرور؟",
    resetPassword: "إسترداد كلمة السر",
    valueMustBeGreeterThan1: "القيمه يجب ان تكون اكبر من ١",
    valueMustBeLessThanRestProposalAmount: "القيمه يجب ان تكون اقل من او يساوي",
    verify: "تاكيد",
    verifyCode: "رمز التحقيق",
    ConfirmPasswordNotMatchedPassword:
      "تأكيد كلمة المرور يجب ان تكون نفس كلمة المرور",
    confirmationSignOut: "هل أنت متأكد من تسجيل الخروج؟",
    shareViaTwitter: "مشاركة عبر تويتر",
    usersCansShareViaTwitter: "يستطيع المستخدمون مشاركة قرض عبر تويتر.",
    approved: "موافق عليه",
    backToHome: "عودة للصفحة الرئيسية",
    home: "الصفحة الرئيسية",
    profile: "الصفحة الشخصية",
    signOut: "تسجيل خروج",
    uploadImage: "تحميل الصورة ",
    UserCanUploadImages: "يمكن للمستخدم تحميل الصور وإضافتها إلى المعرض",
    postUpdate: "إضافه متابعه",
    userCanEditHis:
      "المستخدم يستطيع تعديل القرض في حالة المسودة والذي تم نشرة فقط",
    repaidProposal: "قرض مسدد",
    confirmationDeleteProposal: "هل أنت متأكد من أنك تريد حذف هذا القرض؟",
    confirmationPublish: "هل أنت متأكد من أنك تريد نشر هذا القرض ؟",
    confirmationUnPublish: "هل أنت متأكد من أنك تريد إلغاء نشر هذا القرض ؟",
    confirmationApprove: "هل أنت متأكد من أنك تريد الموافقة على هذا القرض؟",
    confirmationIgnore: "هل أنت متأكد من أنك تريد تجاهل هذا القرض؟",
    confirmationDeleteProposalUpdate:
      "هل أنت متأكد من أنك تريد حذف هذا التعديل؟",
    repaid: "تم تسديده",
    send: "أرسل",
    resendInvitation: "أعاده ارسال دعوة",
    investorPhoto: "صورة المستثمر",
    investorEmail: "عنوان البريد الالكتروني",
    amount: "المبلغ",
    amountToRepay: "قيمة المبلغ المسدد",
    paymentFor: "أدفع ل",
    funded: "المبلغ الممول",
    outstanding: "المبلغ المتبقي",
    paid: "المبلغ المدفوع",
    date: "التاريخ",
    proposalDeletedSucc: "تم حذف القرض بنجاح",
    proposalAlreadyApproved: "تم الموافقة علي القرض سابقا",
    proposalApprovedSucc: "تم الموافقة علي القرض",
    proposalIgnoredSucc: "تم تجاهل القرض بنجاح",
    proposalSavedSucc: "تم حفظ القرض بنجاح",
    proposalUpdatedSucc: "تم تعديل القرض بنجاح",
    proposalPublishedSucc: "تم نشر القرض بنجاح",
    proposalUnPublishedSucc: "تم الغاء نشر القرض بنجاح",
    ignored: "تم التجاهل",
    proposalUnIgnoredSucc: "تم عدم تجاهل القرض بنجاح",
    unignoreProposal: "إلغاء تجاهل القرض ",
    unignoreProposalDesc:
      "يمكن للمستخدم (للمستثمرين ومؤسسات التمويل) إلغاء تجاهل القرض",
    confirmationUnIgnore: "هل أنت متأكد أنك تريد إلغاء تجاهل هذا القرض؟",
    phoneAndEmailAlreadyEx: "رقم الهاتف والبريد الالكتروني مسجلين بالفعل!",
    emailAlreadyExist: "البريد الالكتروني مسجل بالفعل!",
    phoneAlreadyExist: "رقم الهاتف مسجل بالفعل",
    passwordLengthErrorMsg:
      "كلمة مرور غير صحيحة ، كلمة المرور يجب أن تكون على الأقل 8 ارقام.",
    confirmDeleteProposal: "هل أنت متأكد أنك تريد حذف هذا القرض من",
    assignProposalToCampaign: "تعيين هذا الاقتراح إلى الحملة",
    assign: "تعيين",
    campaignRemoved: "تمت إزالة الحملة بنجاح ..",
    addedCampaign: "تمت إضافة الحملة بنجاح ..",
    addCampaign: "أضف حمله",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    invalidDate: "تاريخ غير صحيح",
    campaign: "الحملة",
    viewAllCampaign: "عرض كل الحملات",
    manageCampaigns: "إدارة الحملات",
    campaignTitle: "أسم الحملة",
    campaignUrl: "الموقع الالكتروني للحملة",
    donationUrl: "الموقع الالكتروني للتبرع",
    campaignDesc: "وصف الحمله",
    back: "رجوع",
    viewCampaignProposal: "عرض القروض الخاصة بالحملة",
    publishThisCampaign: "نشر الحملة",
    deleteThisCampaign: "احذف هذه الحملة",
    campaignImage: "صورة الحملة",
    sendEmailToInvestors: "أرسل بريد الإلكتروني إلى المستثمرين",
    updated: "تم الاضافة في",
    sendCode: "ارسل الرمز",
  },
  en: {
    pending: "Pending",
    confirmedByInvestor: "Confirmed by the investor (MFI)",
    loans: "Loans",
    login: "Login",
    borrow: "Borrow",
    invest: "Invest",
    getStart: "Get Started",
    selectLanguage: "Select Language",
    backersListFor: "Backers List For",
    noDataToShow: "No Data To Show",
    loanInformation: "Loan Information",
    totalFunded: "TOTAL FUNDED",
    totalRepaid: "TOTAL REPAID",
    totalRepaidSmall: "Total Repaid",
    totalValue: "Total Value",
    repaidProposals: "Repaid Proposals",
    confirmation: "Confirmation",
    yes: "Yes",
    no: "No",
    addNewProposal: "Add new proposal",
    addNewProposalDesc:
      "-Select this icon to start adding a new proposal This is the first step to get your loan",
    allProposals: "All proposals",
    allProposalsDesc:
      "-Select this icon to see all the proposals Select this to undo the filter effect",
    selectDraftedProposals: "Select drafted proposals",
    selectDraftedProposalsDesc: ` -Select this icon to show only draft proposals. A draft
    proposal is the first status when a proposal is created.
    They are only visible to user who created them only. The
    user can edit and delete a draft proposal till it is
    published.`,
    selectPublishedProposals: "Select Published proposals",
    selectPublishedProposalsDesc: `-Select this icon to show only published proposal A
    Published proposal is the second status when a proposal
    is created. Published proposals are visible for all the
    users and investors User can edit and unpublish the
    published proposal if no one backed it.`,
    selectLockedProposals: "Select Locked proposals",
    selectLockedProposalsDesc: `-Select this icon to show only the locked proposals A
    Locked proposal is the Third status when a proposal is
    created. Locked mean proposal is now backed but not
    fully backed User can’t edit or unpublish his proposal
    User can see, message, and invite backers.`,
    selectBackedProposals: "Select Backed proposals",
    selectBackedProposalsDesc: `-Select this icon to show only the baked proposals A
    Backed proposal is the fourth status when a proposal is
    created. Backed means proposal now is fully backed User
    can’t edit or unpublish his proposal User can see, and
    message backers.`,
    selectFundedProposals: "Select funded proposals",
    selectFundedProposalsDesc: `-Select this icon to show only the Funded proposals A
    Funded Proposal is the Fifth status when a proposal is
    created. Funded means the Liquidity provider approved
    the loan User can withdraw his money to his bank account
    User can’t edit or unpublish his proposal User can see,
    and message backers`,
    selectRepaidProposals: "Select Repaid proposals",
    selectRepaidProposalsDesc: `-Select this icon to show only the Repaid proposals A
    Repaid Proposal is the final status when a proposal is
    created. Repaid means the user is paying his loan
    monthly User can Repay his money User can’t edit or
    unpublish his proposal User can see, and message
    backers.`,
    sendThankYouNote: "Send Thank You Note",
    invitationDate: "Invitation date",
    investedAmount: "Invested Amount",
    active: "Active",
    progress: "Progress",
    openDLNDocs: "Open DLN docs",
    userCanCheckDLNDocumentation: "-User can check DLN documentation",
    phone: "Phone: ",
    email: "Email: ",
    poweredByDLN: "Powered by DLN-DAO",
    investmentIncome: "Investment Income",
    activeROÍ: "Active ROÍ",
    myInvestmentOÍ: "My Investment",
    userName: "User Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    profileImage: "Profile Image",
    firstName: "First Name:",
    lastName: "Last Name:",
    myBio: "My Bio:",
    required: "Required",
    createProfile: "Create Profile",
    iHaveReadAndAgree:
      "I have read and agree to the Terms of Service and Privacy Policy.",
    openHelpMode: "Open Help Mode",
    messageTheInvestors: "Message the investors",
    loanValue: "Loan Value",
    yourAmoutnBackedSucc: "Your Amount Backed Successfully",
    letsInvest: "Let's Invest in ",
    inviteAll: "Invite All",
    letsInviteBackers: "Let's Invite Backers to ",
    repaymentAmount: "Repayment Amount",
    goBack: "Go Back",
    transactionHistory: "TRANSACTION HISTORY",
    withDraw: "Withdraw",
    //proposals card field
    userCanDelete: "-User can delete his drafted and published proposals",
    deleteYourProposal: "Delete your proposal",
    draftedProposal: "Drafted proposal",
    puplishedProposal: "Published proposal",
    saveProposalAsDraft: "save the proposal as a draft",
    saveProposalDesc: "-User can save his proposal as draft",
    lockedProposal: "Locked proposal",
    fundedProposal: "Funded Proposal",
    backedProposal: "Backed Proposal",
    investProposal: "Invest proposal",
    unpublishProposal: "un publish this proposal",
    proposalInProgress: "Proposals In Progress",
    proposalAmount: "proposal Amount",
    proposalDesc: "Proposal Description",
    activeProposals: "Active Proposals",
    totalProposalsValue: "Total Proposal Value",
    proposals: "proposals",
    proposalName: "Proposal name",
    enterAmountOfMoney: "Enter the needed amount of money",
    enterMonthsToRepy: "Enter Months to Repayment",
    monthsToPayment: "Months To Repayment",
    proposalsDate: "Proposal date",
    whenYouNeedToGetYourMoney: "When will you need to get your money?",
    describeYourProposalAndYourNeeds: "Describe your proposal and your needs",
    proposalPic: "Proposal Pic",
    editYourProposal: "Edit your proposal",
    publishYourProposal: "Publish your proposal",
    userCanPublishHisDraftProposal: "-User can publish his draft proposal",
    messageInvestor: "Message investor",
    userCanSelectAnyInvestor: "User can select any investor to send a message",
    inviteAnInvestor: "Invite an investor",
    userCanInviteAnInvestorToBack:
      "-User can invite investors to back his proposal",
    UnpublishYourPublishedProposal: "Unpublish your published proposal",
    unPublishYourProposalsDesc:
      "-User can Unpublish his Published proposal as long as no one backed him yet",
    checkYourBackedAmount: "Check your backed amount",
    collectedAmount: "Collected Amount",
    checkYourBackedAmountDesc:
      "-User can check the amount he collected from backers",
    seeBackers: "Backers list",
    userCanSeeHisBackersDesc:
      "User can see his loan backers This Symbol on (Locked, Funded, and Repaid) Status",
    withDrawYourMoney: "Withdraw your money",
    withDrawHisMoneyDesc:
      "User can withdraw his money Withdraw is from Funded status",
    repayYourLoan: "Repay your loan",
    userCanRepayDesc: "-User can repay his loan on a monthly basis",
    investDesc: "-User can invest in any selected proposal",
    approveProposal: "Approve proposal",
    userCanApproveProposal:
      "-User can approve the proposal Only MFIs can use this",
    ignoreProposal: "Ignore proposal",
    ignoreProposalDesc:
      "-User can Ignore the proposal Investors and MFIs can use this",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    valueMustBeGreeterThan1: "Value must be greater than 1",
    valueMustBeLessThanRestProposalAmount: "Value must be less than or equal",
    verify: "Verify",
    verifyCode: "Verify Code",
    ConfirmPasswordNotMatchedPassword:
      "Confirm Password not matched with password",
    confirmationSignOut: "Are you sure you want to sign out?",
    shareViaTwitter: "Share via Twitter",
    usersCansShareViaTwitter: "Users can share a proposal via twitter.",
    approved: "Approved",
    backToHome: "Back to Home",
    home: "Home",
    profile: "Profile",
    signOut: "Sign Out",
    uploadImage: "Upload image",
    UserCanUploadImages:
      "-User can upload images and add them to the proposal gallery",
    postUpdate: "Post Update",
    userCanEditHis: "-User can edit his drafted and published proposals",
    repaidProposal: "Repaid Proposal",
    confirmationDeleteProposal:
      "Are you sure you want to Delete this proposal?",
    confirmationPublish: "Are you sure you want to publish this proposal?",
    confirmationUnPublish: "Are you sure you want to unpublish this proposal?",
    confirmationApprove: "Are you sure you want to approve this proposal?",
    confirmationIgnore: "Are you sure you want to ignore this proposal?",
    confirmationDeleteProposalUpdate:
      "Are you sure you want to delete this proposal update?",
    repaid: "Repaid",
    send: "Send",
    resendInvitation: "Resend invitation",
    investorPhoto: "Investor Photo",
    investorEmail: "Investor Email",
    amount: "Amount",
    amountToRepay: "Amount To Repay",
    paymentFor: "Payment for",
    funded: "Funded",
    outstanding: "Outsanding",
    paid: "Paid",
    date: "Date",
    proposalDeletedSucc: "Proposal deleted Successfully",
    proposalAlreadyApproved: "Proposal is already Approved",
    proposalApprovedSucc: "Proposal Approved Successfully",
    proposalIgnoredSucc: "Proposal Ignored Successfully",
    proposalSavedSucc: "Proposal Saved Successfully",
    proposalUpdatedSucc: "Proposal updated Successfully",
    proposalPublishedSucc: "Proposal Published Successfully",
    proposalUnPublishedSucc: "Proposal unPublished Successfully",
    ignored: "Ignored",
    proposalUnIgnoredSucc: "Proposal Unignored Successfully",
    unignoreProposal: "Unignore proposal",
    unignoreProposalDesc:
      "-User can Unignore the proposal Investors and MFIs can use this",
    confirmationUnIgnore: "Are you sure you want to unignore this proposal?",
    phoneAndEmailAlreadyEx: "This email and phone are already exist",
    emailAlreadyExist: "This email already exist!",
    phoneAlreadyExist: "This phone already exist!",
    passwordLengthErrorMsg:
      "Invalid Password, Password must be at least 8 characters long.",
    confirmDeleteProposal: "Are you sure you want to delete this proposal from",
    assignProposalToCampaign: "Assign this Proposal to campaign",
    assign: "Assign",
    campaignRemoved: "Campaign removed Successfully..",
    addedCampaign: "the campaign added successfully ..",
    addCampaign: "Add Campaign",
    startDate: "Start Date",
    endDate: "End Date",
    invalidDate: "Invalid Date",
    campaign: "Campaign",
    viewAllCampaign: "View All Campaigns",
    manageCampaigns: "Manage the Campaigns",
    campaignTitle: "Campaign Title",
    campaignUrl: "Campaign URL",
    donationUrl: "Donation URL",
    campaignDesc: "Campaign desc",
    back: "Back",
    viewCampaignProposal: "View Campaign Proposals",
    publishThisCampaign: "Publish this campaign",
    deleteThisCampaign: "Delete this campaign",
    campaignImage: "Campaign Image",
    sendEmailToInvestors: "Send Email to investors",
    updated: "Updated",
    sendCode: "Send Code",
  },
  be: {
    pending: "বিচারাধীন",
    confirmedByInvestor: "বিনিয়োগকারী (প্রতিষ্ঠান) দ্বারা নিশ্চিত",
    loans: "লোন",
    login: "প্রবেশ করুন",
    borrow: "ধার",
    invest: "বিনিয়োগ",
    getStart: "শুরু করা",
    selectLanguage: "ভাষা নির্বাচন কর",
    backersListFor: "জন্য সমর্থনকারীদের তালিকা",
    noDataToShow: "দেখানোর জন্য কোনও ডেটা নেই",
    loanInformation: "লোন সম্পর্কিত তথ্য",
    totalFunded: "মোট তহবিল",
    totalRepaid: "মোট পরিশোধ",
    totalRepaidSmall: "মোট পরিশোধ",
    totalValue: "মোট মূল্য",
    repaidProposals: "পরিশোধের প্রস্তাব",
    confirmation: "Confirmation",
    yes: "হ্যাঁ",
    no: "না",
    addNewProposal: "নতুন প্রস্তাব যোগ করুন ",
    addNewProposalDesc:
      "নতুন প্রস্তাব যোগ করুন - একটি নতুন প্রস্তাব যোগ করা শুরু করতে এই আইকনটি নির্বাচন করুন এটি আপনার লোন পাওয়ার প্রথম ধাপ",
    allProposals: "সব প্রস্তাব",
    allProposalsDesc:
      "সমস্ত প্রস্তাব দেখতে এই আইকনটি নির্বাচন করুন ফিল্টার প্রভাবটি পূর্বাবস্থায় ফেরানোর জন্য এটি নির্বাচন করুন",
    selectDraftedProposals: "খসড়া প্রস্তাবগুলি নির্বাচন করুন ",
    selectDraftedProposalsDesc: `শুধুমাত্র খসড়া প্রস্তাব দেখানোর জন্য এই আইকনটি নির্বাচন করুন।
   কোনও নতুন প্রস্তাব তৈরি হওয়ার পূর্বে খসড়া প্রস্তাবনা হ'ল প্রথম ধাপ।
   এগুলি কেবলমাত্র সেসব ব্যবহারকারীর কাছে দৃশ্যমান যারা এটি তৈরি করেছেন।
   খসড়া প্রস্তাবটি প্রকাশ না হওয়া পর্যন্ত ব্যবহারকারী এটিকে সম্পাদনা এবং মুছতে পারেন`,
    selectPublishedProposals: "প্রকাশনা -প্রকাশিত প্রস্তাবসমূহ নির্বাচন করুন ",
    selectPublishedProposalsDesc: `শুধুমাত্র প্রকাশিত প্রস্তাবনা দেখানোর জন্য এই আইকনটি নির্বাচন করুন।
   কোনও নতুন প্রস্তাব তৈরি হওয়ার সময় প্রকাশিত খসড়া প্রস্তাবনা হ'ল দ্বিতীয় ধাপ।
   প্রকাশিত প্রস্তাবগুলি সকল ব্যবহারকারী এবং বিনিয়োগকারীগণ দেখতে পাবেন।
   যদি কেউ সমর্থন না করে তবে প্রকাশিত প্রস্তাবটি ব্যবহারকারী সম্পাদনা করতে পারেন এবং তা অপ্রকাশিতও রাখতে পারেন। `,
    selectLockedProposals: "লক করা প্রস্তাবগুলি নির্বাচন করুন",
    selectLockedProposalsDesc: `শুধুমাত্র লক করা প্রস্তাবগুলি দেখানোর জন্য এই আইকনটি নির্বাচন করুন
   কোনও নতুন প্রস্তাব তৈরি হওয়ার সময় লকড প্রস্তাবনা হ'ল তৃতীয় ধাপ।
   লকড-এর অর্থ আংশিক সমর্থিত হয়েছে তবে পুরোপুরি নয়
   ব্যবহারকারী তার প্রস্তাবটি সম্পাদনা বা অপ্রকাশিত করতে পারবেন না।
   ব্যবহারকারীগণ সম্পাদনা, বার্তা প্রেরণ এবং সমর্থনকারীদের আমন্ত্রণ জানাতে পারেন`,
    selectBackedProposals: "সমর্থন - সমর্থনযুক্ত প্রস্তাব নির্বাচন করুন ",
    selectBackedProposalsDesc: `শুধুমাত্র লক করা প্রস্তাবগুলি দেখানোর জন্য এই আইকনটি নির্বাচন করুন
   কোনও নতুন প্রস্তাব তৈরি হওয়ার সময় সমর্থিত প্রস্তাবনা হ'ল চতুর্থ ধাপ।
   ব্যাকড- এর অর্থ এখন প্রস্তাবটি পুরোপুরি সমর্থিত হয়েছে। 
   ব্যবহারকারী তার প্রস্তাবটি সম্পাদনা বা অপ্রকাশিত করতে পারবেন না
   ব্যবহারকারীরা দেখতে পাবেন এবং সমর্থনকারীদের বার্তা দিতে পারবেন।`,
    selectFundedProposals: "অর্থায়িত - তহবিল প্রস্তাব নির্বাচন করুন",
    selectFundedProposalsDesc: `শুধুমাত্র অর্থের প্রস্তাবগুলি দেখানোর জন্য এই আইকনটি নির্বাচন করুন
   কোনও নতুন প্রস্তাব তৈরি হওয়ার সময় অর্থায়িত প্রস্তাবনা হ'ল পঞ্চম ধাপ।
   অর্থায়িত -এর অর্থ লিকুইডিটি প্রদানকারী লোন অনুমোদন করেছেন। 
   ব্যবহারকারী তার ব্যাংক অ্যাকাউন্ট থেকে তার টাকা তুলতে পারবেন
   ব্যবহারকারী তার প্রস্তাবটি সম্পাদনা বা অপ্রকাশিত করতে পারবেন না
   ব্যবহারকারীরা দেখতে পাবেন এবং সমর্থনকারীদের বার্তা দিতে পারবেন।`,
    selectRepaidProposals: "পরিশোধ- পরিশোধিত প্রস্তাবগুলি নির্বাচন করুন",
    selectRepaidProposalsDesc: `কেবল অর্থ পরিশোধের প্রস্তাবগুলি দেখানোর জন্য এই আইকনটি নির্বাচন করুন
   যখন কোনও প্রস্তাব তৈরি করা হয় তখন পরিশোধ হল চূড়ান্ত 
   পরিশোধের অর্থ ব্যবহারকারী তার লোন মাসিক কিস্তিতে পরিশোধ করবেন 
   ব্যবহারকারী তার লোনের অর্থ ফেরত দেবেন। 
   ব্যবহারকারী তার প্রস্তাবটি সম্পাদনা বা অপ্রকাশিত করতে পারবেন না
   ব্যবহারকারীরা দেখতে পাবেন এবং সমর্থনকারীদের বার্তা দিতে পারবেন।`,
    sendThankYouNote: "ধন্যবাদ নোট প্রেরণ করুন",
    invitationDate: "আমন্ত্রণের তারিখ",
    investedAmount: "বিনিয়োগের পরিমাণ",
    active: "সক্রিয়",
    progress: "অগ্রগতি",
    openDLNDocs: "খুলুন ডিএলএন ডক্স",
    userCanCheckDLNDocumentation:
      "ব্যবহারকারী ডিএলএন ডকুমেন্টেশন পর্যবেক্ষণ করতে পারেন",
    phone: "ফোন ",
    email: "ইমেল ",
    poweredByDLN: "চালিত DLN-DAO",
    investmentIncome: "বিনিয়োগ আয়",
    activeROÍ: "সক্রিয় ROÍ",
    myInvestmentOÍ: "আমার বিনিয়োগ",
    userName: "ব্যবহারকারীর নাম",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    firstName: "নাম",
    lastName: "পদবি",
    myBio: "প্রোফাইল ছবি",
    profileImage: "প্রোফাইল ছবি",
    iHaveReadAndAgree:
      "আমি পরিষেবার শর্তাদি এবং গোপনীয়তা নীতি পড়েছি এবং তাতে সম্মত হয়েছি।",
    createProfile: "প্রোফাইল তৈরি করুন",
    required: "আবশ্যক",
    openHelpMode: "সহায়তার জন্য ডেমো খুলুন",
    messageTheInvestors: "বিনিয়োগকারীদের বার্তা দিন",
    loanValue: "লোন মূল্য",
    yourAmoutnBackedSucc: "আপনার পরিমাণ সাফল্যের সাথে ব্যাকড হয়েছে",
    letsInvest: "আসুন বিনিয়োগ করা যাক",
    inviteAll: "আমন্ত্রণ জানান",
    letsInviteBackers: "আসুন ব্যাকারদের আমন্ত্রণ জানাই",
    repaymentAmount: "পরিশোধের পরিমাণ",
    goBack: "ফিরে যাও",
    transactionHistory: "আপনি কি আমার সাথে কি করতে চান",
    withDraw: "প্রত্যাহার",
    //proposals card field
    userCanDelete:
      "-ব্যবহারকারী তার খসড়া এবং প্রকাশিত প্রস্তাবগুলি মুছে দিতে পারেন",
    deleteYourProposal: "আপনার প্রস্তাব মুছে দিন",
    draftedProposal: "খসড়া প্রস্তাব",
    puplishedProposal: "প্রকাশিত প্রস্তাব",
    lockedProposal: "তালাবন্ধ প্রস্তাব",
    fundedProposal: "অর্থায়িত প্রস্তাব",
    backedProposal: "প্রস্তাবিত প্রস্তাব",
    investProposal: "বিনিয়োগের প্রস্তাব",
    unpublishProposal: "এই প্রস্তাবটি প্রকাশ না করা",
    saveProposalAsDraft: "একটি খসড়া হিসাবে প্রস্তাব সংরক্ষণ করুন",
    saveProposalDesc:
      "আপনার প্রস্তাব সংরক্ষণ করুন - ব্যবহারকারী তার প্রস্তাবটি খসড়া হিসাবে সংরক্ষণ করতে পারবেন",
    proposalInProgress: "প্রস্তাবগুলির অগ্রগতি",
    proposalAmount: "প্রস্তাবের পরিমাণ",
    proposalDesc: "প্রস্তাবনা বিবরণ",
    activeProposals: "সক্রিয় প্রস্তাব",
    totalProposalsValue: "মোট প্রস্তাব মূল্য",
    proposals: "প্রস্তাব",
    proposalName: "প্রস্তাবের নাম",
    enterAmountOfMoney: "প্রয়োজনীয় অর্থের পরিমান",
    enterMonthsToRepy: "লোন পরিশোধের সময় (মাস)",
    monthsToPayment: "লোন পরিশোধের সময়",
    proposalsDate: "প্রস্তাবের তারিখ",
    whenYouNeedToGetYourMoney: "আপনার টাকা কখন প্রয়োজন? ",
    describeYourProposalAndYourNeeds:
      "আপনার প্রস্তাব এবং আপনার প্রয়োজনীয়তা বর্ণনা করুন",
    proposalPic: "প্রস্তাবের ছবি",
    editYourProposal: "সম্পাদনা- আপনার প্রস্তাবটি সম্পাদনা করুন",
    publishYourProposal: '"প্রকাশনা- আপনার প্রস্তাব প্রকাশ করুন',
    userCanPublishHisDraftProposal:
      "ব্যবহারকারী তার খসড়া প্রস্তাবটি প্রকাশ করতে পারেন",
    messageInvestor: "বিনিয়োগকারীকে বার্তা ",
    userCanSelectAnyInvestor:
      "ব্যবহারকারী কোনও বার্তা প্রেরণের জন্য যে কোনও বিনিয়োগকারী নির্বাচন করতে পারেন",
    inviteAnInvestor: "একজন বিনিয়োগকারীকে আমন্ত্রণ করুন",
    userCanInviteAnInvestorToBack:
      "ব্যবহারকারী তার প্রস্তাবটি ফিরে পেতে বিনিয়োগকারীদের আমন্ত্রণ জানাতে পারেন",
    UnpublishYourPublishedProposal:
      "অপ্রকাশিত → আপনার প্রকাশিত প্রস্তাব অপ্রকাশ করুন",
    unPublishYourProposalsDesc:
      "ব্যবহারকারীর প্রকাশিত প্রস্তাবটি সমর্থিত না হওয়া পর্যন্ত তার প্রস্তাবটি অপ্রকাশিত রাখতে পারেন।",
    checkYourBackedAmount:
      "সমর্তিথের পরিমাণ- আপনার সমর্তিথের পরিমাণটি পরীক্ষা করুন",
    collectedAmount: "সংগৃহীত পরিমাণ",
    checkYourBackedAmountDesc:
      "ব্যবহারকারীগণ সমর্থকদের কাছ থেকে যে পরিমাণ অর্থ সংগ্রহ করেছিলেন তা পরীক্ষা করতে পারেন",
    seeBackers: "সমর্থকদের তালিকা- আপনার সমর্থকদের তালিকা দেখুন",
    userCanSeeHisBackersDesc:
      "ব্যবহারকারী তার লোন সমর্থনকারীদের দেখতে পারেন প্রতীক অনুযায়ী (লকড, অর্থায়িত এবং পরিশোধিত) স্থিতি",
    withDrawYourMoney: "আপনার অর্থ উত্তোলন করুন",
    withDrawHisMoneyDesc:
      "ব্যবহারকারী তার অর্থ উত্তোলন করতে পারেন তহবিল থেকে অর্থের উত্তোলন",
    repayYourLoan: "পরিশোধ- আপনার লোন পরিশোধ করুন",
    userCanRepayDesc: "ব্যবহারকারী মাসিক কিস্তিতে তার লোন পরিশোধ করতে পারেন ",
    investDesc: " ব্যবহারকারী যে কোনও নির্বাচিত প্রস্তাবে বিনিয়োগ করতে পারেন",
    approveProposal: "প্রস্তাব অনুমোদন করুন",
    userCanApproveProposal:
      "ব্যবহারকারী প্রস্তাবটি অনুমোদন করতে পারবে কেবলমাত্র এমএফআইগুলিই এটি ব্যবহার করতে পারে ",
    ignoreProposal: "প্রস্তাব উপেক্ষা করুন",
    ignoreProposalDesc:
      "ব্যবহারকারী প্রস্তাব উপেক্ষা করতে পারেন বিনিয়োগকারী এবং এমএফআইগুলি এটি ব্যবহার করতে পারে",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন ?",
    resetPassword: "পাসওয়ার্ড রিসেট করুন",
    valueMustBeGreeterThan1: "মান একের চেয়ে বেশি হতে হবে",
    valueMustBeLessThanRestProposalAmount: "মান কম বা সমান হতে হবে",
    verify: "যাচাই করুন",
    verifyCode: "কোড যাচাই করুন",
    ConfirmPasswordNotMatchedPassword:
      "নিশ্চিত করুন পাসওয়ার্ড পাসওয়ার্ডের সাথে মিলছে না",
    confirmationSignOut: "আপনি সাইন আউট করতে চান?",
    shareViaTwitter: "টুইটারের মাধ্যমে শেয়ার করুন",
    usersCansShareViaTwitter:
      "ব্যবহারকারীরা টুইটারের মাধ্যমে একটি প্রস্তাব শেয়ার করতে পারেন।.",
    approved: "অনুমোদিত",
    backToHome: "বাড়িতে ফিরে যাও",
    home: "বাড়ি",
    profile: "প্রোফাইল",
    signOut: "সাইন আউট",
    uploadImage: "ছবি আপলোড করুন ",
    UserCanUploadImages:
      "-ব্যবহারকারী ছবি আপলোড করতে পারেন এবং প্রস্তাব গ্যালারিতে যোগ করতে পারেন",
    postUpdate: "পোস্ট আপডেট করা হয়েছে",
    userCanEditHis:
      "ব্যবহারকারী তার খসড়া এবং প্রকাশিত প্রস্তাবগুলি সম্পাদনা করতে পারবেন",
    repaidProposal: "শোধ করা .ণ",
    confirmationDeleteProposal: "আপনি কি এই প্রস্তাবটি মুছে ফেলতে চান?",
    confirmationPublish: "আপনি কি এই প্রস্তাবটি প্রকাশ করতে চান?",
    confirmationUnPublish:
      "আপনি কি এই প্রস্তাবটি অপ্রকাশিত করার ব্যাপারে নিশ্চিত?",
    confirmationApprove: "আপনি কি এই প্রস্তাবটি অনুমোদন করার ব্যাপারে নিশ্চিত?",
    confirmationIgnore: "আপনি কি এই প্রস্তাবটি উপেক্ষা করতে চান?",
    confirmationDeleteProposalUpdate: "আপনি কি এই প্রস্তাবটি মুছে ফেলতে চান?",
    repaid: "পরিশোধ",
    send: "পাঠান",
    resendInvitation: "পুনরায় পাঠান আমন্ত্রণ",
    investorPhoto: "বিনিয়োগকারীর ছবি",
    investorEmail: "বিনিয়োগকারীর ইমেল",
    amount: "পরিমাণ",
    amountToRepay: "শোধ করার পরিমাণ",
    paymentFor: "জন্য পেমেন্ট",
    funded: "তহবিল",
    outstanding: "অসামান্য",
    paid: "পরিশোধিত",
    date: "তারিখ স্ট্যাম্প",
    proposalDeletedSucc: "প্রস্তাব সফলভাবে মুছে ফেলা হয়েছে",
    proposalAlreadyApproved: "প্রস্তাব ইতিমধ্যে অনুমোদিত",
    proposalApprovedSucc: "প্রস্তাব সফলভাবে অনুমোদিত হয়েছে",
    proposalIgnoredSucc: "প্রস্তাব সফলভাবে উপেক্ষা করা হয়েছে",
    proposalSavedSucc: "প্রস্তাব সফলভাবে সংরক্ষিত হয়েছে",
    proposalUpdatedSucc: "প্রস্তাব সফলভাবে আপডেট করা হয়েছে",
    proposalPublishedSucc: "প্রস্তাবনা সফলভাবে প্রকাশিত হয়েছে",
    proposalUnPublishedSucc: "প্রস্তাবনা সফলভাবে প্রকাশিত হয়নি",
    ignored: "উপেক্ষা করা",
    proposalUnIgnoredSucc: "পরামর্শ সফলভাবে বাতিল করা হয়েছে",
    unignoreProposal: "বাতিল করার পরামর্শ বাতিল করুন",
    unignoreProposalDesc:
      "ব্যবহারকারী (বিনিয়োগকারী এবং অর্থায়নকারী প্রতিষ্ঠানের জন্য) উপেক্ষা করা পরামর্শ বাতিল করতে পারেন",
    confirmationUnIgnore: "আপনি কি এই পরামর্শটি পূর্বাবস্থায় ফেরাতে চান?",
    phoneAndEmailAlreadyEx: "এই ইমেল এবং ফোন ইতিমধ্যে বিদ্যমান!",
    emailAlreadyExist: "এই ইমেলটি ইতিমধ্যে বিদ্যমান!",
    phoneAlreadyExist: "এই ফোনটি ইতিমধ্যে বিদ্যমান!",
    passwordLengthErrorMsg:
      "ভুল পাসওয়ার্ড, পাসওয়ার্ড কমপক্ষে 8 ডিজিটের হতে হবে",
    confirmDeleteProposal:
      "আপনি কি নিশ্চিত যে আপনি এই প্রস্তাবটি মুছে দিতে চান?",
    assignProposalToCampaign: "এই প্রস্তাবটি ক্যাম্পেইনে অর্পণ করুন",
    assign: "বরাদ্দ করুন",
    campaignRemoved: "ক্যাম্পেইন সফলভাবে সরানো হয়েছে ..",
    addedCampaign: "ক্যাম্পেইন সফলভাবে যোগ করা হয়েছে ..",
    addCampaign: "অ্যাড ক্যাম্পেইন",
    startDate: "শুরুর তারিখ",
    endDate: "শেষ তারিখ",
    invalidDate: "অবৈধ তারিখ",
    campaign: "প্রচারণা",
    viewAllCampaign: "সমস্ত প্রচারাভিযান দেখুন",
    manageCampaigns: "প্রচারাভিযানগুলি পরিচালনা করুন",
    campaignTitle: "প্রচারাভিযান নাম",
    campaignUrl: "প্রচারাভিযানের URL",
    donationUrl: "অনুদান URL:",
    campaignDesc: "ক্যাম্পেইনের বর্ণনা",
    back: "পেছনে",
    viewCampaignProposal: "ক্যাম্পেইন প্রস্তাব দেখুন",
    publishThisCampaign: "এই প্রচারটি প্রকাশ করুন",
    deleteThisCampaign: "এই ক্যাম্পেইনটি মুছে দিন",
    campaignImage: "প্রচারাভিযানের ছবি",
    sendEmailToInvestors: "বিনিয়োগকারীদের ইমেল পাঠান",
    updated: "যোগ করা হয়েছে",
    sendCode: "কোড পাঠান",
  },
});
export default strings;
