/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cloud_logic_custom: [
    {
      name: "auth",
      endpoint: "https://pk4f8g5bpi.execute-api.us-east-1.amazonaws.com/dev",
      region: "us-east-1",
    },
  ],
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_qnNuBn9jx",
  aws_user_pools_web_client_id: "42i1djhnseg3p2qgg6p35ncd69",
  oauth: {},
};

export default awsmobile;
